### PR TITLE
Update DOCS.md

### PR DESCRIPTION
**Pull request by baylanger**
Made few changes per my experience, specially the popup error after shutting down Flask.

I can make adjustment per your comments.

### CODE REVIEW

**Comment by baylanger** [comment]
Just to make sure, you also get this popup after shutting down Flask?

IMG_1331

**Question for the nginx step:**
. Customize the Nginx add-on configuration like this and then restart it.
As soon as I hit the Restart, this error pops up:
> Failed to restart add-on
> Unknown error, see supervisor logs
Are you getting that too? My understanding is that bcause this container is used by most people (everyone?) to access the HA UI, it probably exits w/ non-0 code on purpose for the Watchdog to restart it. Even if I hit "Stop", I get that popup so it's definitely not an error at Start. Should we put a comment for people not to be too nervous?

**The following 2 steps:**
. Start this add-on and wait for it to initialize. It will fail with an error because Nginx is not configured correctly.
. Restart this add-on and this time it should succeed.
Somehow I never got any error and I'm not sure why. With the "Shutdown Flask" popup error above, I ended up uninstall/re-install the add-on ~4-5 times until I realized there was no issue... so I wonder if the error you refer in this step is actually the Nginx restart error that I mentioned just above?

**Comment by peterhow11** [comment]
I can confirm that this is the error message that I was getting on "Shutdown Flask". I was operating in the HA app on iOS.  After clicking "No", you get an empty page with a "502 error" from which I wasn't able to exit using the back-arrow at the top-left. Closing and restarting the HA app kept returning me to that page so I was stuck there. I finally uninstalled and re-installed the HA app to get back to normal usage.

**Comment by baylanger** [comment]
If I recall, could go back using arrow at top. Note this is with iOS 17.4 beta. I’ll try to test again tomorrow. Wonder if it’s same experience on Android.

Reposting « full » image showing the arrow. 

IMG_1306

**Comment by baylanger** [comment]
Maybe it’s possible to redirect the app to the add-on main page after pressing the shutdown Flask?

**Comment by llamafilm** [comment]
> Maybe it’s possible to redirect the app to the add-on main page after pressing the shutdown Flask?

Yeah this would be much better UX. I tried, but couldn’t figure it out using HTML. I’m going to try again using JavaScript before accepting this PR.

And the back arrow works for me, I just had to press it twice and ack the error.

**Comment by llamafilm** [comment]
Thank you for your suggestions.  I pushed a change today that avoids the 502 errors by restarting the addon instead, and rearranged several things.  I incorporated some of your proposed changes, so I'm going to close this now.  Let me know if anything still needs work.

**Comment by baylanger** [comment]
The only thing that quickly comes in mind is for the docker command to work, the "advanced terminal/ssh" add-on is required - just to minimize anyone to raise an issue

I learned of the advance add-on ~ 6 weeks ago ... and for ~2y, I couldn't understand why haos wasn't permitting access to docker commands only to realized I needed that one.

**Pull request closed without merging**
